# Uncomment the next line to define a global platform for your project
platform :ios, '7.0'

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Invites'
pod 'Firebase/RemoteConfig'
pod 'Firebase/Storage'

target 'Chatty' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Chatty

end
